# Generated by Django 4.2.6 on 2023-11-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_produit', models.IntegerField()),
            ],
        ),
    ]
