# Generated by Django 4.2.6 on 2023-11-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('statue_commande', models.CharField(choices=[('attente', 'en attente'), ('non livré', 'non livré'), ('livré', 'livré')], default='attente', max_length=255)),
                ('quantite', models.PositiveSmallIntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', to_field='nom')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
            ],
        ),
    ]
