# Generated by Django 4.2.6 on 2023-11-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_product_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
            ],
        ),
    ]
