# Generated by Django 4.2.6 on 2023-11-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_product_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
    ]
