# Generated by Django 4.2.6 on 2023-11-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaires',
            options={'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
    ]
