# Generated by Django 4.2.6 on 2023-11-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='id_product_service',
        ),
        migrations.RemoveField(
            model_name='commentaires',
            name='username',
        ),
        migrations.AddField(
            model_name='commentaires',
            name='email_user_commentaire',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
