# Generated by Django 4.2.6 on 2023-11-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='services',
            name='stock',
        ),
        migrations.AddField(
            model_name='services',
            name='prix_discutable',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='prix_normal',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
