# Generated by Django 4.2.6 on 2023-11-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_services_prix_remove_services_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='prix_discutable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='prix_normal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
