# Generated by Django 5.0.4 on 2024-05-04 00:40

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_prix_discutable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=services.models.rename_img)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Mini Service',
                'verbose_name_plural': 'Mini Services',
            },
        ),
    ]
