# Generated by Django 5.0.4 on 2024-05-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_miniservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniservice',
            name='mini_decription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
