# Generated by Django 5.0.4 on 2024-05-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_miniservice_mini_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
            preserve_default=False,
        ),
    ]
