# Generated by Django 5.0.4 on 2024-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_miniservice_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniservice',
            old_name='mini_decription',
            new_name='mini_description',
        ),
        migrations.AddField(
            model_name='miniservice',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
