# Generated by Django 5.0.4 on 2024-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_mini_decription_miniservice_mini_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniservice',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
