# Generated by Django 4.2.6 on 2023-11-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletters',
            options={'verbose_name': 'News Letter', 'verbose_name_plural': 'News Letters'},
        ),
        migrations.AlterModelOptions(
            name='utilisateurs',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='id',
        ),
        migrations.AddField(
            model_name='newsletters',
            name='id_email_news_letter',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
