# Generated by Django 5.0.4 on 2024-05-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
        ('services', '0004_miniservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services'),
        ),
    ]
