# Generated by Django 5.0.4 on 2024-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
